server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CitizenDB_Microservice_Demo
    username: root
    password: krishnendu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: CITIZEN-SERVICE
